kind: Deployment
apiVersion: apps/v1
metadata:
  name: sftp
  namespace: sftp
  labels:
    app: sftp
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: sftp
  template:
    metadata:
      labels:
        deployment: sftp
    spec:
      volumes:
        - name: sftp-etc-sftp
          configMap:
            name: sftp-etc-sftp
            defaultMode: 420
        - name: sftp-etc-ssh
          configMap:
            name: sftp-etc-ssh
            defaultMode: 384
        - name: sftp
          persistentVolumeClaim:
            claimName: sftp
      containers:
        - name: sftp
          image: >-
             quay.io/rhn_support_rmarques/sftp:v1
          ports:
            - containerPort: 22
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: sftp-etc-sftp
              mountPath: /etc/sftp
            - name: sftp-etc-ssh
              mountPath: /etc/ssh
            - name: sftp
              mountPath: /home/bar/upload
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
